var W_vvv=new Array(101,101,101,101,101,101,101,101,101,101,101);
var W_vvvv=new Array(101,101,101,101,101,101);
var ttN;
var Autor=new Array();
var Kafedra=new Array();
var Organisation=new Array();
var Kol_v=new Array();
var mas=new Array();
var mas_PHP=new Array();
var Name_tema=new Array();
var tema_N=new Array();
var Name_razdel=new Array();
var Razdel=new Array();
var ldiv=document.getElementsByTagName('div');
//var ldiv=document.all.tags('div');
var isNC=false;
var isNC6=false;
var PPP_T;
var isOld=false;
var isIE=false;
var QQQ=new Array();
var da="ÄÀÒÀ";
var wrr="ÂÐÅÌß";
var QQ=new Array();
var name_browser=navigator.appName;
if(name_browser=="Netscape") isNC=true;
                                              else    isIE=true;
var num_version=parseInt(navigator.appVersion.charAt(0));
if(isNC && num_version>=6) isNC6=true;
if(num_version<4) isOld=true;

